name: Publish to GitHub Packages

on:
  workflow_run:
    # This must match the `name` of the manual release workflow to Central
    workflows: [ "Manual Release" ]
    types: [ completed ]

jobs:
  publish-github:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout main HEAD
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages (Maven)
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
